<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>cable_bringup</name>
  <version>0.1.0</version>
  <description>Launch files for the SOFA cable + UR5e Gazebo simulation</description>
  <maintainer email="miko.boucherika@gmail.com">Bouchrikator</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ur5e_ts_ibvs_description</exec_depend>
  <exec_depend>sofa_ros2_adapter</exec_depend>
  <exec_depend>gazebo_cable_visual</exec_depend>
  <exec_depend>cable_identification</exec_depend>
  <exec_depend>cable_perception</exec_depend>
  <exec_depend>cable_ts_control</exec_depend>
  <exec_depend>ibvs_control</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
